name: java-app
run-name: java-app workflow
on: 
  push:
    paths:
      - 'java-app/**'
      - '.github/workflows/java-app.yml'
jobs:
  building-java-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java-app Test run
        run: | 
          date
          ls -la
          pwd 
          echo "CIAO---------------------------------"
          env
      - name: Set up JDK for x64
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'temurin'
          architecture: x64
      - name: mvn versione
        run: mvn -version
      - name: java versione
        run: java -version
      - run: mvn test 
        working-directory: ./java-app/my-app
